pub(crate) mod about;
pub(crate) mod dashboard;
mod dashboard_import;
pub(crate) mod editor;
pub(crate) mod editor_controls;
mod editor_obj_panel;
pub(crate) mod editor_toolbar;
mod layer_dialogs;
pub(crate) mod layers;
pub(crate) mod objects;
pub(crate) mod properties;
pub(crate) mod save_dialog;
pub(crate) mod settings;
pub(crate) mod themes;
mod tile_palette;
pub(crate) mod tilesets;
pub(crate) mod widgets;
